- name: create a new EC2 key pair, returns generated private key
  amazon.aws.ec2_key:
    name: "{{ key_name }}-public"
  register: key_info

- debug:
    msg:
      - "{{ key_info }}"

- name: Save Private Key to directory
  copy:
    dest: "{{ config_dir }}/{{ key_name }}-private"
    mode: 600
    owner: "ashishmahawal"
    content: |
      {{ key_info.key.private_key }}
