- name: Fetch VPC Id from VPC Name
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_info

- debug:
    msg: 
      - "{{ vpc_info }}"

- set_fact:
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"


- name: Create subnet for database servers
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ cidr }}"
    tags:
      Name: "{{ subnet_name }}"
  register: subnet_info

- debug:
    msg:
      - "Subnet 1 Info ....... {{ subnet_info }}"