- name: Fetch VPC info
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_info

- name: Set vpc_id
  set_fact:
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    state: absent
    vpc_id: "{{ vpc_id }}"