name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hola
        run: echo "Github Actions Workflow Job triggered"
      - name: Check Working dir
        run: pwd
