name: CI-workflow
on: push
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          sudo apt-get install yamllint
      - name: Clone the Repo
        uses: actions/checkout@v3

      - name: List dir
        run: |
          echo Checking env $GITHUB_WORKSPACE 
          ls
      - name: Linter Check
        run: |
          yamllint ./roles/
          