name: CI-workflow
on:
  pull_request:
    branches: 
      - "dev-*"
      - "main"
      - "master"
      - "test*"
  push:
    branches:
      - "main"
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          sudo apt-get install yamllint
      - name: Clone the Repo
        uses: actions/checkout@v3
      
      - name: Cache Cloned repo
        uses: actions/cache@v3
        with:
          path: ../aws_cloud_automation
          key: cloned-repo-${{ hashFiles('**/roles') }}

      - name: List dir
        run: |
          echo Checking env $GITHUB_WORKSPACE 
          ls
      - name: Linter Check
        run: |
          yamllint ./roles/
  build_collection:
    needs: [lint_check]
    runs-on: ubuntu-latest
    steps:
      - name: Cache Cloned repo
        uses: actions/cache@v3
        with:
          path: ../aws_cloud_automation
          key: cloned-repo-${{ hashFiles('**/roles') }}
      - name: Git Clone
        uses: actions/checkout@v3
      - name: Build Ansible collection
        run: ansible-galaxy collection build --output-path ./output --force
      - name: Upload to Ansible Galaxy
        run: echo "Requires API Token"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: roles-collection
          path: |
            output
            README.md
      - name: Make use of previous Job Var out
        run: echo "${{ needs.lint_check.outputs.test-var }}"
