name: CI-workflow
on: workflow_dispatch
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: |
          sudo apt-get install yamllint
          ls

      - name: Linter Check
        run: |
          yamllint .
          